# Generated by Django 3.1.4 on 2020-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='', upload_to='image_posts/'),
        ),
    ]
