# Generated by Django 3.1.4 on 2021-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210102_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meme',
            field=models.ImageField(default=1, upload_to='image_posts'),
            preserve_default=False,
        ),
    ]
