# Generated by Django 3.1.4 on 2021-01-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_meme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meme',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
