# Generated by Django 3.1.6 on 2021-02-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
